import Foundation

public enum AdvPayloadDecoder {
    public struct Field: Sendable, Equatable { public let label:String; public let value:String; public init(_ label:String,_ value:String){self.label=label;self.value=value} }
    public struct RoleHint: Sendable, Equatable { public let bucket:String; public let label:String; public let reason:String; public let weight:Int; public init(bucket:String,label:String,reason:String,weight:Int){self.bucket=bucket;self.label=label;self.reason=reason;self.weight=weight} }

    public static func decodeManufacturer(_ record:MfgRecord)->[Field] {
        guard let b=hexToBytes(record.dataHex) else{return []}
        switch record.companyId { case 0x004C:return decodeApple(b); case 0x0006:return decodeMicrosoft(b); case 0x0157:return decodeAltBeacon(b); case 0x00E0:return [Field("Google manufacturer data","\(b.count) bytes")]; default:return [] }
    }
    public static func decodeService(_ record:ServiceDataRecord)->[Field] {
        guard let b=hexToBytes(record.dataHex),let u=uuid16(record.uuid) else{return []}
        switch u { case 0xFE2C:return decodeFastPair(b); case 0xFEAA:return decodeEddystone(b); default:return [] }
    }
    public static func roleHints(_ device:Sighting)->[RoleHint] {
        var out=[RoleHint]()
        let mfg=device.facts.mfgRecords.isEmpty ? (device.manufacturerId.map{[MfgRecord(companyId:$0,dataHex:device.manufacturerDataHex)]} ?? []) : device.facts.mfgRecords
        for rec in mfg where rec.companyId == 0x004C {
            guard let bytes=hexToBytes(rec.dataHex) else{continue}
            for t in appleTLVs(bytes) {
                switch t.type {
                case 0x02 where t.data.count >= 20:
                    // FIX-AD1: Kotlin يفرّق ثلاثة: Tesla (وزن 8) · Target/Atrius (وزن 8) · iBeacon عام (7).
                    let h=hex(t.data).uppercased(), tesla=DefaultCatalogConstants.teslaIBeaconMfgPrefix.uppercased()
                    let atrius=DefaultCatalogConstants.targetAtriusIBeaconMfgPrefix.uppercased()
                    if h.hasPrefix(tesla) || h.hasPrefix(String(tesla.dropFirst(4))) { out.append(RoleHint(bucket:"vehicle",label:"a Tesla vehicle or phone-as-key",reason:"Tesla phone-key iBeacon UUID (iOS background find).",weight:8)) }
                    else if h.hasPrefix(atrius) || h.hasPrefix(String(atrius.dropFirst(4))) { out.append(RoleHint(bucket:"beacon",label:"a Target Atrius basket tag",reason:"Target / Atrius iBeacon UUID (shopping-basket asset tag).",weight:8)) }
                    else { out.append(RoleHint(bucket:"beacon",label:"an iBeacon",reason:"Apple iBeacon payload.",weight:7)) }
                case 0x05: out.append(RoleHint(bucket:"phone",label:"an iPhone or iPad offering AirDrop",reason:"Apple AirDrop advertisement.",weight:5))
                case 0x07: let model=airPodsModel(t.data); out.append(RoleHint(bucket:"audio-personal",label:model ?? "AirPods or Beats headphones",reason:model == nil ? "Apple Proximity Pairing (AirPods / Beats)." : "Apple Proximity Pairing: \(model!).",weight:8))
                case 0x08: out.append(RoleHint(bucket:"siri",label:"an Apple device that just heard “Hey Siri”",reason:"Hey Siri advertisement.",weight:6))
                case 0x09: out.append(RoleHint(bucket:"audio-speaker",label:"an AirPlay speaker or Apple TV",reason:"AirPlay advertisement.",weight:5))
                case 0x0B: out.append(RoleHint(bucket:"phone",label:"an Apple device doing Handoff",reason:"Handoff advertisement.",weight:4))
                case 0x0C: out.append(RoleHint(bucket:"phone",label:"an Apple device looking for Instant Hotspot",reason:"Tethering-target advertisement.",weight:5))
                case 0x0D,0x0E: out.append(RoleHint(bucket:"hotspot",label:"an iPhone/iPad offering Instant Hotspot",reason:"Tethering-source advertisement.",weight:6))
                case 0x0F: out.append(RoleHint(bucket:"phone",label:"an Apple device (Nearby Action)",reason:nearbyActionReason(t.data),weight:4))
                case 0x10: out.append(RoleHint(bucket:"phone",label:"an iPhone / iPad / Mac (Nearby Info)",reason:nearbyInfoReason(t.data),weight:5))
                case 0x12: out.append(RoleHint(bucket:"tag",label:"a Find My network radio",reason:"Apple Offline Finding — AirTag, Find My accessory, or an Apple device locating itself.",weight:4))
                default: break
                }
            }
        }
        for sd in device.facts.serviceData {
            guard let u=uuid16(sd.uuid),let b=hexToBytes(sd.dataHex) else{continue}
            if u == 0xFE2C {
                // FIX-AD2: Kotlin يستدعي FastPairModels.name — الاسم إن وُجد بوزن 8، وإلا وزن 6.
                if b.count==3 {
                    let id=modelId24(b), nm=FastPairModels.name(id)
                    out.append(RoleHint(bucket:"audio-personal",
                        label:nm ?? "a Fast Pair accessory (often earbuds or a speaker)",
                        reason:nm != nil ? String(format:"Google Fast Pair model %@ (0x%06X), in pairing mode.",nm!,id)
                                         : String(format:"Google Fast Pair model 0x%06X, in pairing mode.",id),
                        weight:nm != nil ? 8 : 6))
                } else { out.append(RoleHint(bucket:"audio-personal",label:"a Fast Pair accessory already paired to someone",reason:"Google Fast Pair account-key broadcast (not in pairing mode).",weight:4)) } }
            if u == 0xFEAA { let f=b.first ?? 0; if f==0x40 || f==0x41 { out.append(RoleHint(bucket:"tag",label:"a Google Find Hub tag",reason:f==0x41 ? "Find Hub separated (unwanted-tracking) frame." : "Find Hub nearby frame.",weight:8)) } else { out.append(RoleHint(bucket:"beacon",label:"an Eddystone beacon",reason:"Eddystone service data.",weight:6)) } }
        }
        return out
    }

    private struct TLV { let type:Int; let data:[UInt8] }
    private static func appleTLVs(_ bytes:[UInt8])->[TLV] { var out=[TLV](),i=0; while i+2<=bytes.count { let t=Int(bytes[i]),n=Int(bytes[i+1]); guard n>0 && i+2+n<=bytes.count else{break}; out.append(TLV(type:t,data:Array(bytes[(i+2)..<(i+2+n)]))); i += 2+n }; return out }
    private static func decodeApple(_ bytes:[UInt8])->[Field] {
        let tlvs=appleTLVs(bytes); guard !tlvs.isEmpty else{return [Field("Apple payload","\(bytes.count) bytes (unparsed)")]}; var out=[Field]()
        for t in tlvs { out.append(Field("Apple Continuity type",String(format:"0x%02X · %@",t.type,appleTypeName(t.type)))); switch t.type {
        case 2:out += decodeIBeacon(t.data); case 5:out += decodeAirDrop(t.data); case 6:out += [Field("HomeKit","\(t.data.count) bytes of HomeKit setup data")]; case 7:out += decodeAirPods(t.data); case 8:out += decodeHeySiri(t.data); case 9:out += [Field("AirPlay","This device is advertising as an AirPlay source or target.")]; case 10:out += [Field("Magic Switch","Apple Watch wrist / unlock related.")]; case 11:out += decodeHandoff(t.data); case 12:out += decodeHandoffOrTetherTarget(t.data); case 13,14:out += decodeTetherSource(t.data); case 15:out += decodeNearbyAction(t.data); case 16:out += decodeNearbyInfo(t.data); case 18:out += decodeFindMy(t.data); default:out += [Field("Payload","\(t.data.count) bytes")] }
        }; return out
    }
    private static func appleTypeName(_ t:Int)->String { [2:"iBeacon",3:"AirPrint",5:"AirDrop",6:"HomeKit",7:"Proximity Pairing (AirPods / Beats)",8:"Hey Siri",9:"AirPlay",10:"Magic Switch (Watch)",11:"Handoff",12:"Handoff or Instant Hotspot (target)",13:"Instant Hotspot (source)",14:"Instant Hotspot (source)",15:"Nearby Action",16:"Nearby Info",18:"Find My / Offline Finding",19:"Nearby Action (extended)",22:"Nearby Info"][t] ?? "unlisted" }
    private static func decodeIBeacon(_ data:[UInt8])->[Field] { let body=(data.count>=22 && data[0]==0x15) ? Array(data[1..<22]) : (data.count>=21 ? Array(data[0..<21]) : []); guard body.count>=21 else{return [Field("iBeacon","truncated (\(data.count) bytes)")]}; let uuid=uuidFromBE(body,0); let tesla=uuid.filter{$0.isLetter||$0.isNumber}.lowercased()==String(DefaultCatalogConstants.teslaIBeaconMfgPrefix.dropFirst(4)).lowercased(); return [Field("iBeacon UUID",tesla ? "\(uuid) — Tesla phone-as-key (iOS background find). Not a mall beacon." : uuid),Field("iBeacon major / minor","\(u16be(body,16)) / \(u16be(body,18))"),Field("iBeacon calibrated TX","\(Int(Int8(bitPattern:body[20]))) dBm at 1 m (used to estimate range)")] }
    private static func decodeAirDrop(_ data:[UInt8])->[Field] { guard data.count>=18 else{return [Field("AirDrop","Someone nearby is offering AirDrop (\(data.count) bytes).")]}; return [Field("AirDrop","Someone nearby has AirDrop receiving on. Hashes are truncated IDs, not names."),Field("Apple ID hash (2 bytes)",hex(Array(data[9..<11])).uppercased())] }
    private static func decodeAirPods(_ data:[UInt8])->[Field] { guard data.count>=5 else{return [Field("AirPods","Proximity Pairing, truncated.")]}; let start=data[0]==1 ? 1:0; guard data.count>=start+4 else{return [Field("AirPods","Proximity Pairing.")]}; let model=Int(data[start])<<8|Int(data[start+1]), status=Int(data[start+2]), batt=Int(data[start+3]), left=batt&15,right=(batt>>4)&15; var out=[Field("Product",airPodsModelName(model) ?? String(format:"Apple audio 0x%04X",model)),Field("Pod position",airPodsStatus(status)),Field("Battery (left / right)","\(nibblePct(left)) / \(nibblePct(right))")]; if data.count>start+4 { let ch=Int(data[start+4]), cb=ch&15; out.append(Field("Case battery",nibblePct(cb))); var c=[String](); if ch&0x10 != 0{c.append("case")};if ch&0x20 != 0{c.append("right")};if ch&0x40 != 0{c.append("left")};if !c.isEmpty{out.append(Field("Charging",c.joined(separator:", ")))}};if data.count>start+6{out.append(Field("Color",airPodsColor(Int(data[start+6]))))};return out }
    private static func airPodsModel(_ data:[UInt8])->String? { guard data.count>=4 else{return nil};let s=data[0]==1 ? 1:0;guard data.count>=s+2 else{return nil};return airPodsModelName(Int(data[s])<<8|Int(data[s+1])) }
    private static func airPodsModelName(_ id:Int)->String? { [0x0220:"AirPods (1st generation)",0x0F20:"AirPods (2nd generation)",0x1320:"AirPods (3rd generation)",0x1920:"AirPods (4th generation)",0x1C20:"AirPods 4",0x0E20:"AirPods Pro",0x1420:"AirPods Pro (2nd generation)",0x2420:"AirPods Pro 2 (USB-C)",0x1F20:"AirPods Max",0x0A20:"Beats Solo3",0x0B20:"Powerbeats 3",0x0C20:"Beats Studio Buds",0x0D20:"Beats Fit Pro",0x1020:"Powerbeats Pro",0x1120:"Beats Studio Buds +",0x1220:"Beats Solo Pro",0x1720:"Beats Flex",0x1A20:"Beats Studio Pro",0x1B20:"Beats Fit Pro",0x0520:"BeatsX",0x0920:"Beats Studio³ Wireless",0x1620:"Beats Studio Buds +",0x2520:"Beats Solo 4",0x2620:"Beats Solo Buds",0x2D20:"AirPods Max 2",0x3820:"Beats 360",0x038F:"Beats Studio Buds"][id] }
    private static func airPodsStatus(_ s:Int)->String { [1:"One or both out of the case",2:"Case open",3:"Taken out / in-ear transition",5:"One in ear",9:"Both out, not in ear",11:"In-ear activity",17:"Both in ear",19:"Both in ear",33:"One in ear (sharing?)",81:"Both in case, lid open",85:"Both in case, lid closed",117:"In case"][s] ?? String(format:"Status 0x%02X",s) }
    private static func airPodsColor(_ v:Int)->String { [0:"White",1:"Black",2:"Red",3:"Blue",4:"Pink",5:"Gray",6:"Silver",7:"Gold",8:"Rose gold",9:"Space gray",10:"Dark blue",11:"Light blue",12:"Yellow"][v] ?? String(format:"0x%02X",v) }
    private static func nibblePct(_ n:Int)->String { switch n{case 0...9:return "\(n*10)%";case 10...14:return "100%";case 15:return "unknown / not present";default:return "\(n)"} }
    private static func decodeHeySiri(_ data:[UInt8])->[Field] { guard data.count>=6 else{return [Field("Hey Siri","Siri was just triggered on a nearby Apple device.")]};let k=u16be(data,4);let d:[Int:String]=[2:"iPhone",3:"iPad",7:"HomePod",9:"Mac",10:"Watch"];return [Field("Hey Siri","A \(d[k] ?? String(format:"class 0x%04X",k)) just heard a Siri trigger. The packet carries a short voice hash, not the words.")] }
    private static func decodeHandoff(_ data:[UInt8])->[Field] { [Field("Handoff","Continuity Handoff: a task can be continued on another Apple device. Payload is encrypted.")] }
    private static func decodeHandoffOrTetherTarget(_ data:[UInt8])->[Field] { data.count>=14 ? decodeHandoff(data) : [Field("Instant Hotspot (looking)","This Apple device is searching for a paired phone’s hotspot.")] }
    private static func decodeTetherSource(_ data:[UInt8])->[Field] { guard data.count>=6 else{return [Field("Instant Hotspot","An iPhone/iPad is offering a personal hotspot.")]};let batt=Int(data[2]),cell=u16be(data,3),bars=Int(data[5]);let cn:[Int:String]=[0:"4G",6:"4G",1:"1xRTT",2:"GPRS",3:"EDGE",4:"3G",5:"3G",7:"LTE",8:"5G"];var s="Paired iPhone/iPad hotspot";if batt<=100{s += " · phone battery \(batt)%"};if let x=cn[cell]{s += " · \(x)"}else{s += " · type \(cell)"};if bars<=5{s += " · \(bars)/5 bars"};return [Field("Instant Hotspot (offering)",s)] }
    private static func decodeNearbyAction(_ data:[UInt8])->[Field] { if data.isEmpty{return [Field("Nearby Action","Apple Nearby Action")]};let a=data.count>=2 ? Int(data[1]) : Int(data[0]);return [Field("Nearby Action",nearbyActionName(a))] }
    private static func nearbyActionReason(_ data:[UInt8])->String { guard data.count>=2 else{return "Nearby Action advertisement."};return "Nearby Action: \(nearbyActionName(Int(data[1])))." }
    private static func nearbyActionName(_ a:Int)->String { [1:"Apple TV setup",4:"Mobile backup",5:"Watch setup",6:"Apple TV pair",8:"Wi-Fi password sharing (prompting nearby iPhones)",9:"iOS setup",10:"Repair",11:"Speaker setup",12:"Apple Pay",13:"Whole-home audio setup",15:"Answered a call",16:"Ended a call",19:"Remote AutoFill",20:"Companion Link proximity",23:"Remote display"][a] ?? String(format:"action 0x%02X",a) }
    private static func decodeNearbyInfo(_ data:[UInt8])->[Field] { guard !data.isEmpty else{return [Field("Nearby Info","Apple device usage state.")]};let status=Int(data[0]),action=status&15,hi=(status>>4)&15,flags=data.count>1 ? Int(data[1]):0;let activity:[Int:String]=[0:"activity unknown",1:"activity reporting off",3:"idle (screen locked)",5:"audio playing, screen locked",7:"active (screen on)",9:"screen on, video playing",10:"Watch on wrist and unlocked",11:"recent interaction",13:"user is driving",14:"phone or FaceTime call"];var s=(activity[action] ?? String(format:"activity 0x%X",action)).prefix(1).uppercased()+String((activity[action] ?? String(format:"activity 0x%X",action)).dropFirst());var e=[String]();if hi&1 != 0{e.append("primary iCloud device")};if hi&4 != 0{e.append("AirDrop receiving on")};if flags&4 != 0{e.append("Wi-Fi on")};if flags&1 != 0{e.append("AirPods connected")};if flags&32 != 0{e.append("Watch locked")};if !e.isEmpty{s += ". "+e.joined(separator:"; ")};s += ".";return [Field("What the Apple device is doing",s)] }
    private static func nearbyInfoReason(_ data:[UInt8])->String { guard let x=data.first else{return "Nearby Info advertisement."};switch Int(x)&15{case 3:return "Phone is idle / locked.";case 5:return "Audio playing with the screen locked.";case 7:return "Screen is on — someone is using it.";case 13:return "Device reports the user is driving.";case 14:return "In a phone or FaceTime call.";default:return "Nearby Info advertisement."} }
    private static func decodeFindMy(_ data:[UInt8])->[Field] { guard !data.isEmpty else{return [Field("Find My","Offline Finding advertisement.")]};let st=Int(data[0]),maintained=st&4 != 0,b=(st>>6)&3;let bn:[Int:String]=[0:"full",1:"medium",2:"low",3:"critical"];let n=max(0,data.count-1);return [Field("Find My / Offline Finding","Broadcasting a public key so the Find My network can report a location. Used by AirTags, Find My accessories, and Apple devices locating themselves. \(maintained ? "Owner seen recently." : "Owner not seen in the current key window.") Battery \(bn[b] ?? "unknown"). (\(n)-byte key fragment — not a serial number.)")] }
    private static func decodeFastPair(_ b:[UInt8])->[Field] { if b.count==3{let id=modelId24(b), nm=FastPairModels.name(id);return [Field("Google Fast Pair","In pairing mode — Android will pop a tap-to-pair card."),Field("Model ID", nm != nil ? String(format:"%@  (0x%06X)",nm!,id) : String(format:"0x%06X (not in the local name list)",id))]};guard !b.isEmpty else{return []};let vf=Int(b[0]),version=(vf>>4)&15;var ui="account-key bloom filter";if b.count>1{switch Int(b[1])&15{case 0:ui="wants to show a pairing card";case 2:ui="hiding the pairing card (e.g. buds back in the case)";default:ui="filter type \(Int(b[1])&15)"}};return [Field("Google Fast Pair","Already paired to an account (not in pairing mode). \(ui). Version \(version).")] }
    private static func decodeEddystone(_ b:[UInt8])->[Field] { guard let f=b.first else{return []};switch Int(f){case 0:guard b.count>=18 else{return [Field("Eddystone-UID","truncated")]};return [Field("Eddystone-UID namespace",hex(Array(b[2..<12]))),Field("Eddystone-UID instance",hex(Array(b[12..<18])))];case 16:return [Field("Eddystone-URL",eddystoneURL(b) ?? "\(b.count) bytes")];case 32:return [Field("Eddystone-TLM","telemetry (battery / temperature / advert count)")];case 48:return [Field("Eddystone-EID","ephemeral ID (rotating)")];case 64,65:let n=max(0,min(b.count-1,b.count>=33 ? 32 : (b.count>=21 ? 20 : b.count-1)));return [Field("Find Hub",Int(f)==65 ? "separated (unwanted-tracking mode)" : "nearby / with owner"),Field("Find Hub EID",n>0 ? hex(Array(b[1..<(1+n)])) : "\(b.count) bytes")];default:return [Field("Eddystone",String(format:"frame 0x%02X",f))]}}
    private static func eddystoneURL(_ b:[UInt8])->String? { guard b.count>=3 else{return nil};let p:[Int:String]=[0:"http://www.",1:"https://www.",2:"http://",3:"https://"];guard let pre=p[Int(b[2])] else{return nil};let ex=[".com/",".org/",".edu/",".net/",".info/",".biz/",".gov/",".com",".org",".edu",".net",".info",".biz",".gov"];var s=pre;for c in b.dropFirst(3){let x=Int(c);if x<ex.count{s+=ex[x]}else if x>=0x20&&x<=0x7E{s.append(Character(UnicodeScalar(x)!))}};return s}
    private static func decodeMicrosoft(_ b:[UInt8])->[Field] { guard !b.isEmpty else{return []};if b[0]==1 && b.count>=2{let t=Int(b[1])&31;let n:[Int:String]=[1:"Xbox",6:"iPhone",7:"iPad",8:"Android",9:"Windows desktop",11:"Windows phone",12:"Linux",13:"Windows IoT",14:"Surface Hub",15:"Windows laptop",16:"Windows tablet"];return [Field("Microsoft Nearby Sharing / Swift Pair","A \(n[t] ?? "type \(t)") is advertising for quick pairing or sharing.")]};return [Field("Microsoft manufacturer data","\(b.count) bytes")] }
    private static func decodeAltBeacon(_ b:[UInt8])->[Field] { guard b.count>=22,b[0]==0xBE,b[1]==0xAC else{return []};return [Field("AltBeacon UUID",uuidFromBE(b,2)),Field("AltBeacon major / minor","\(u16be(b,18)) / \(u16be(b,20))")] }
    private static func modelId24(_ b:[UInt8])->Int { Int(b[0])<<16|Int(b[1])<<8|Int(b[2]) }
    private static func u16be(_ b:[UInt8],_ i:Int)->Int { Int(b[i])<<8|Int(b[i+1]) }
    private static func uuidFromBE(_ b:[UInt8],_ o:Int)->String { let h=b[o..<o+16].map{String(format:"%02x",$0)}.joined();return "\(h.prefix(8))-\(h.dropFirst(8).prefix(4))-\(h.dropFirst(12).prefix(4))-\(h.dropFirst(16).prefix(4))-\(h.dropFirst(20))" }
    private static func uuid16(_ s:String)->Int? { let h=s.filter{$0.isLetter||$0.isNumber}.uppercased();if h.count==4{return Int(h,radix:16)};if h.count==32 && h.hasPrefix("0000") && h.hasSuffix("00001000800000805F9B34FB"){return Int(String(h.dropFirst(4).prefix(4)),radix:16)};return nil }
    private static func hexToBytes(_ s:String)->[UInt8]? { let h=s.filter{$0.isLetter||$0.isNumber};guard !h.isEmpty,h.count%2==0 else{return nil};return stride(from:0,to:h.count,by:2).compactMap{Int(String(h[h.index(h.startIndex,offsetBy:$0)..<h.index(h.startIndex,offsetBy:$0+2)]),radix:16).map(UInt8.init)} }
    private static func hex(_ b:[UInt8])->String { b.map{String(format:"%02X",$0)}.joined() }
}
