import Foundation

// ملاحظة: MacUtil انتقلت إلى CoreSupport.swift بنسخة أمينة لـ Models.kt:870
// (نسخة هذا الملف كانت تقصّ إلى 12 خانة وتُرجع "" للعناوين القصيرة — تخالف Kotlin)

public struct LogRadio: Sendable, Equatable {
    public let kind:RadioKind; public let mac:String; public let name:String; public let vendor:String?; public let manufacturerId:Int?; public let manufacturerDataHex:String; public let serviceUuids:[String]; public let vendorIeOuis:[String]; public let randomized:Bool; public let hiddenSsid:Bool; public let rssi:Int; public let firstSeen:Int64; public let lastSeen:Int64; public let hits:Int; public let channel:Int; public let frequencyMhz:Int; public let latitude:Double?; public let longitude:Double?
    public init(kind:RadioKind,mac:String,name:String,vendor:String?=nil,manufacturerId:Int?=nil,manufacturerDataHex:String="",serviceUuids:[String]=[],vendorIeOuis:[String]=[],randomized:Bool=false,hiddenSsid:Bool=false,rssi:Int = -100,firstSeen:Int64=0,lastSeen:Int64=0,hits:Int=1,channel:Int=0,frequencyMhz:Int=0,latitude:Double?=nil,longitude:Double?=nil){self.kind=kind;self.mac=mac;self.name=name;self.vendor=vendor;self.manufacturerId=manufacturerId;self.manufacturerDataHex=manufacturerDataHex;self.serviceUuids=serviceUuids;self.vendorIeOuis=vendorIeOuis;self.randomized=randomized;self.hiddenSsid=hiddenSsid;self.rssi=rssi;self.firstSeen=firstSeen;self.lastSeen=lastSeen;self.hits=hits;self.channel=channel;self.frequencyMhz=frequencyMhz;self.latitude=latitude;self.longitude=longitude}
    public var key:String { "\(kind.rawValue):\(mac)" }; public var hasPosition:Bool {latitude != nil && longitude != nil}
    public var hasStructuredId:Bool { !nameGlob().isEmpty || vendorIeOuis.contains(where:{ $0.filter{$0.isNumber || ($0.isLetter && $0.isASCII)}.count >= 6 }) || (kind == .ble && !serviceUuids.isEmpty) || (kind == .ble && manufacturerId != nil && !manufacturerDataHex.isEmpty) }
    private func nameGlob()->String { SignatureCandidates.nameGlobOf(name) ?? "" }
    public func toSighting()->Sighting { Sighting(key:key,kind:kind,mac:mac,name:name,rssi:rssi,rssiMin:rssi,rssiMax:rssi,channel:channel,frequencyMhz:frequencyMhz,vendor:vendor,randomized:randomized,hiddenSsid:hiddenSsid,serviceUuids:serviceUuids,manufacturerId:manufacturerId,manufacturerDataHex:manufacturerDataHex,rawHex:manufacturerDataHex,firstSeen:firstSeen,lastSeen:lastSeen,hitCount:hits,fleetIds:[],latitude:latitude,longitude:longitude,vendorIeOuis:vendorIeOuis) }
}

public enum LogReplay {
    public static let defaultCSVHeader=["timestamp","iso","kind","mac","name","rssi","channel","freq","oui","vendor","fleets","mfg","uuids","flags","raw","lat","lon","vendor_ie"]
    public static func parse(_ text:String)->[LogRadio] { var a:[String:LogRadio]=[:]; let clean=text.replacingOccurrences(of:"\0",with:""); let first=clean.split(whereSeparator:\.isNewline).first(where:{!$0.trimmingCharacters(in:.whitespaces).isEmpty})?.trimmingCharacters(in:.whitespaces) ?? ""; ingest(clean.split(whereSeparator:\.isNewline).map(String.init),json:first.hasPrefix("{"),acc:&a); return Array(a.values) }
    public static func ingest<S:Sequence>(_ lines:S,json:Bool,acc:inout [String:LogRadio]) where S.Element==String { var header:[String]?; for raw in lines { let line=raw.replacingOccurrences(of:"\0",with:"").trimmingCharacters(in:.whitespacesAndNewlines); guard !line.isEmpty else{continue}; if json { if line.first=="{" { ingestJSON(line,&acc) }; continue }; if header == nil { if line.hasPrefix("timestamp") {header=splitCSV(line);continue}; header=defaultCSVHeader }; ingestCSV(line,header!,&acc) } }
    public static func lineKind(_ line:String,json:Bool,header:[String]=defaultCSVHeader)->RadioKind? { if json {guard let d=try? JSONSerialization.jsonObject(with:Data(line.utf8)) as? [String:Any],let k=d["kind"] as? String else{return nil};return RadioKind(rawValue:k)}; let c=splitCSV(line); guard let i=header.firstIndex(of:"kind"),i<c.count else{return nil};return RadioKind(rawValue:c[i].trimmingCharacters(in:.whitespaces)) }
    public static func csvRowToJSON(_ line:String,header:[String]=defaultCSVHeader)->String? { let c=splitCSV(line); func v(_ n:String)->String {guard let i=header.firstIndex(of:n),i<c.count else{return ""};return c[i]}; guard let k=RadioKind(rawValue:v("kind").trimmingCharacters(in:.whitespaces)) else{return nil}; var o:[String:Any]=["ts":Int64(v("timestamp")) ?? 0,"iso":v("iso"),"kind":k.rawValue,"mac":v("mac"),"name":v("name"),"rssi":Int(v("rssi")) ?? -100,"channel":Int(v("channel")) ?? 0,"freq":Int(v("freq")) ?? 0,"oui":v("oui"),"vendor":v("vendor"),"fleets":v("fleets"),"raw":v("raw"),"uuids":v("uuids").replacingOccurrences(of:"|",with:","),"vendor_ie":v("vendor_ie"),"rand":v("flags").uppercased().contains("RAND"),"hidden":v("flags").uppercased().contains("HIDDEN")]; if let m=Int(v("mfg"),radix:16){o["mfg"]=m}; if let x=Double(v("lat")){o["lat"]=x};if let x=Double(v("lon")){o["lon"]=x}; guard JSONSerialization.isValidJSONObject(o),let d=try? JSONSerialization.data(withJSONObject:o,options:[]) else{return nil}; return String(data:d,encoding:.utf8) }
    public static func jsonRowToCSV(_ line:String)->String? { guard let d=try? JSONSerialization.jsonObject(with:Data(line.utf8)) as? [String:Any],let k=d["kind"] as? String,(k=="WIFI" || k=="BLE") else{return nil}; func s(_ n:String)->String {d[n] as? String ?? ""}; let flags="\((d["rand"] as? Bool)==true ? "RAND " : "")\((d["hidden"] as? Bool)==true ? "HIDDEN" : "")".trimmingCharacters(in:.whitespaces); let m=d["mfg"].map{String(describing:$0)} ?? ""; let uu=s("uuids").replacingOccurrences(of:",",with:"|"); let vals:[String]=[String(describing:d["ts"] ?? 0),s("iso"),k,s("mac"),s("name").replacingOccurrences(of:",",with:" "),String(describing:d["rssi"] ?? -100),String(describing:d["channel"] ?? 0),String(describing:d["freq"] ?? 0),s("oui"),s("vendor").replacingOccurrences(of:",",with:" "),s("fleets").replacingOccurrences(of:",",with:" "),m,uu,flags,s("raw"),s("lat"),s("lon"),s("vendor_ie")]; return vals.joined(separator:",") }
    private static func ingestCSV(_ line:String,_ h:[String],_ a:inout [String:LogRadio]) {let c=splitCSV(line);func v(_ n:String)->String{guard let i=h.firstIndex(of:n),i<c.count else{return ""};return c[i]};guard let kind=RadioKind(rawValue:v("kind").trimmingCharacters(in:.whitespaces)) else{return};let mac=MacUtil.normalize(v("mac"));guard !mac.isEmpty else{return};let flags=v("flags").uppercased();let mfg=Int(v("mfg"),radix:16) ?? Int(v("mfg"));let r=LogRadio(kind:kind,mac:mac,name:v("name").trimmingCharacters(in:.whitespaces),vendor:v("vendor").trimmingCharacters(in:.whitespaces).nilIfEmpty,manufacturerId:mfg,manufacturerDataHex:v("raw"),serviceUuids:v("uuids").split{ $0=="|" || $0==","}.map(String.init),vendorIeOuis:v("vendor_ie").split(separator:"|").map{normalizeOUI(String($0))}.filter{!$0.isEmpty},randomized:flags.contains("RAND") || MacUtil.isRandomized(mac),hiddenSsid:flags.contains("HIDDEN"),rssi:Int(v("rssi")) ?? -100,firstSeen:Int64(v("timestamp")) ?? 0,lastSeen:Int64(v("timestamp")) ?? 0,hits:1,channel:Int(v("channel")) ?? 0,frequencyMhz:Int(v("freq")) ?? 0,latitude:Double(v("lat")),longitude:Double(v("lon")));merge(r,&a)}
    private static func ingestJSON(_ line:String,_ a:inout [String:LogRadio]) {guard let d=try? JSONSerialization.jsonObject(with:Data(line.utf8)) as? [String:Any],let k=d["kind"] as? String,let kind=RadioKind(rawValue:k),let raw=d["mac"] as? String else{return};let mac=MacUtil.normalize(raw);guard !mac.isEmpty else{return};let r=LogRadio(kind:kind,mac:mac,name:d["name"] as? String ?? "",vendor:(d["vendor"] as? String)?.nilIfEmpty,manufacturerId:d["mfg"] as? Int,manufacturerDataHex:d["raw"] as? String ?? "",serviceUuids:(d["uuids"] as? String ?? "").split{ $0=="|" || $0==","}.map(String.init),vendorIeOuis:(d["vendor_ie"] as? String ?? "").split(separator:"|").map{normalizeOUI(String($0))}.filter{!$0.isEmpty},randomized:d["rand"] as? Bool ?? MacUtil.isRandomized(mac),hiddenSsid:d["hidden"] as? Bool ?? false,rssi:d["rssi"] as? Int ?? -100,firstSeen:d["ts"] as? Int64 ?? Int64(d["ts"] as? Int ?? 0),lastSeen:d["ts"] as? Int64 ?? Int64(d["ts"] as? Int ?? 0),hits:1,channel:d["channel"] as? Int ?? 0,frequencyMhz:d["freq"] as? Int ?? 0,latitude:d["lat"] as? Double,longitude:d["lon"] as? Double);merge(r,&a)}
    private static func merge(_ r:LogRadio,_ a:inout [String:LogRadio]) {guard let p=a[r.key] else{a[r.key]=r;return};a[r.key]=LogRadio(kind:r.kind,mac:r.mac,name:r.name.isEmpty ? p.name:r.name,vendor:r.vendor ?? p.vendor,manufacturerId:r.manufacturerId ?? p.manufacturerId,manufacturerDataHex:r.manufacturerDataHex.isEmpty ? p.manufacturerDataHex:r.manufacturerDataHex,serviceUuids:Array(Set(p.serviceUuids+r.serviceUuids)),vendorIeOuis:Array(Set(p.vendorIeOuis+r.vendorIeOuis)),randomized:p.randomized || r.randomized,hiddenSsid:p.hiddenSsid || r.hiddenSsid,rssi:r.rssi,firstSeen:min(p.firstSeen==0 ? r.firstSeen:p.firstSeen,r.firstSeen),lastSeen:max(p.lastSeen,r.lastSeen),hits:p.hits+r.hits,channel:r.channel != 0 ? r.channel:p.channel,frequencyMhz:r.frequencyMhz != 0 ? r.frequencyMhz:p.frequencyMhz,latitude:r.latitude ?? p.latitude,longitude:r.longitude ?? p.longitude)}
    private static func splitCSV(_ s:String)->[String] {s.split(separator:",",omittingEmptySubsequences:false).map(String.init)}
}
private extension String { var nilIfEmpty:String? {isEmpty ? nil:self} }

private func normalizeOUI(_ raw:String)->String { let h=raw.filter{$0.isNumber || ($0.isLetter && $0.isASCII)}.uppercased(); guard h.count>=6 else{return ""}; let x=String(h.prefix(6)); return stride(from:0,to:6,by:2).map{String(x[x.index(x.startIndex,offsetBy:$0)..<x.index(x.startIndex,offsetBy:$0+2)])}.joined(separator:":") }
